### ISSUE TITLE
Could ppo train pick and place task?

### ISSUE THREAD

**Issue by Rancho-zhao** [zeyang23/panda_robot_task#1]
I use ppo in stable_baselines3 to trian `FetchPickAndPlace-v1` in gym robotics env, but after 5e6 time steps, it's reward didn't improve.
So could ppo train pick and place task? My train code is like this:
```
import gym

from stable_baselines3 import PPO

from stable_baselines3.common.env_util import make_vec_env

from stable_baselines3.common.callbacks import CheckpointCallback

env_id = 'FetchPickAndPlace-v1'

num_cpu = 4
vec_env = make_vec_env(env_id, n_envs=num_cpu)

log_dir = './tensorboard/' + env_id

checkpoint_callback = CheckpointCallback(save_freq=25000, save_path='model_checkpoints/'+env_id,
                                         name_prefix=env_id)

total_timesteps = 5000000

# PPO
model = PPO(policy="MultiInputPolicy", env=vec_env, verbose=1, normalize_advantage=True,
            tensorboard_log=log_dir)

model.learn(total_timesteps=total_timesteps, callback=checkpoint_callback)

model.save('./trained/'+env_id+'/'+env_id+model.__class__.__name__)
```

**Comment by zeyang23** [comment]
Hello~
I haven't used Fetch envs before, but I think ppo should work on FetchPickAndPlace. You may need to adjust your parameters carefully, which has significant effect on training. Besides, you may need to try several seeds on the same set of parameters because of the randomness in RL. For Fetch envs, rl-baselines3-zoo provides tuned parameters and trained agents, see https://github.com/DLR-RM/rl-baselines3-zoo

**Comment by Rancho-zhao** [comment]
Okay, thank you for your reply!
